export const Tasks = [
    { id: '1', goalId: '1', title: 'Buy balloons', completed: false },
    { id: '2', goalId: '1', title: 'Order cake', completed: true },
    { id: '3', goalId: '1', title: 'Book party venue', completed: false },
    { id: '4', goalId: '1', title: 'Send invitations', completed: true },
    { id: '5', goalId: '1', title: 'Arrange decorations', completed: false },
    { id: '6', goalId: '1', title: 'Confirm DJ', completed: true },
    { id: '7', goalId: '2', title: 'Draft agenda', completed: false },
    { id: '8', goalId: '2', title: 'Send invites', completed: true },
    { id: '9', goalId: '2', title: 'Book venue', completed: false },
    { id: '10', goalId: '2', title: 'Prepare presentation', completed: true },
    { id: '11', goalId: '2', title: 'Confirm speakers', completed: false },
    { id: '12', goalId: '3', title: 'Run 5km', completed: false },
    { id: '13', goalId: '3', title: 'Do strength training', completed: false },
    { id: '14', goalId: '3', title: 'Schedule workout sessions', completed: true },
    { id: '15', goalId: '3', title: 'Buy running shoes', completed: true },
    { id: '16', goalId: '4', title: 'Buy new shoes', completed: true },
    { id: '17', goalId: '4', title: 'Register for the marathon', completed: false },
    { id: '18', goalId: '4', title: 'Join running group', completed: true },
    { id: '19', goalId: '4', title: 'Plan training schedule', completed: false },
    { id: '20', goalId: '5', title: 'Prepare presentation slides', completed: true },
    { id: '21', goalId: '5', title: 'Book conference room', completed: false },
    { id: '22', goalId: '5', title: 'Send meeting agenda', completed: true },
    { id: '23', goalId: '5', title: 'Confirm attendees', completed: false },
    { id: '24', goalId: '6', title: 'Write report', completed: true },
    { id: '25', goalId: '6', title: 'Review financial statements', completed: false },
    { id: '26', goalId: '6', title: 'Prepare budget plan', completed: true },
    { id: '27', goalId: '6', title: 'Schedule review meeting', completed: false },
    { id: '28', goalId: '7', title: 'Organize team meeting', completed: true },
    { id: '29', goalId: '7', title: 'Update project plan', completed: false },
    { id: '30', goalId: '7', title: 'Allocate resources', completed: true },
    { id: '31', goalId: '7', title: 'Review progress', completed: false },
    { id: '32', goalId: '7', title: 'Prepare status report', completed: true }
  ];
  